env:
  es2020: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 11
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: {}
overrides:
  - files: '*.js'
    env:
      node: true
  - files: '*.ts'
    env:
      browser: true
  - files: '*.spec.ts'
    env:
      jest: true
