name: Verify project patterns

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint Commit Messages 🔧
        uses: wagoid/commitlint-github-action@v2.0.2

      - name: Use Node.js ${{ matrix.node-version }} 🔧
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install 🔧
        run: |
          npm i -g yarn
          yarn

      - name: Lint code style 🔧
        run: yarn lint
