name: Verify project patterns 👮🏿

on:
  push:
    branches-ignore:
      - master
      - next
      - docs

jobs:
  patterns:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint commit messages 🕵️
        uses: wagoid/commitlint-github-action@v2

      - name: Use cache Yarn 🚚
        uses: actions/cache@v2
        env:
          cache-name: cache-yarn
        with:
          path: ~/.yarn/berry/cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}

      - name: Use cache NPM 🚚
        uses: actions/cache@v2
        env:
          cache-name: cache-npm
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Use Node.js ${{ matrix.node-version }} 🧰
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies 🔧
        run: |
          npm i -g yarn
          yarn

      - name: Lint code style 🕵️
        run: yarn lint

      - name: Run tests 🧪
        run: yarn coverage
