name: Release NPM & GitHub

on:
  push:
    branches:
      - master
      - next

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Cache yarn
        uses: actions/cache@v2
        env:
          cache-name: cache-yarn
        with:
          path: ~/.yarn/berry/cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}

      - name: Cache npm
        uses: actions/cache@v2
        env:
          cache-name: cache-npm
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Use Node.js ${{ matrix.node-version }} 🔧
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install 🔧
        run: |
          npm i -g yarn
          yarn

      - name: Lint code style 🔧
        run: yarn lint

      - name: Verify tests and coverage 🔧
        run: yarn coverage

      - name: Build 🔧
        run: |
          yarn build

      - name: Release 🚀
        env:
          GH_TOKEN: ${{secrets.GH_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        run: yarn release -d
